language: node_js

node_js:
  - "8.11"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp-cli
script: gulp build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
